# 선형대수학 연습 코딩

In [1]:
print("hello")

hello


## 행렬을 표현해보자. 


In [6]:
## 형렬 연산을 위해 필요한 import들

import numpy as np

In [13]:
asList = [1,2,3]
asArray = np.array(asList)
rowVec = np.array([[1,2,3]])
colVec = rowVec.T
print(f'rowVec : {rowVec.shape}')
print(f'colVec : {colVec.shape}')

rowVec : (1, 3)
colVec : (3, 1)


### 벡터의 합  

In [14]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6])
plus = u + v + w
print(plus)

[14 28 42]


In [16]:
##this is broadcasting
v = np.array([[4,5,6]])
w = np.array([[10,20,30]])
print(v+w.T)

[[14 15 16]
 [24 25 26]
 [34 35 36]]


In [23]:
## 리스트반복과 스칼라곱

s = 2 
a = [3,4,5]
b = np.array(a)
print(a*s)
print(s*b)
print(s+b)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]
[5 6 7]


### 벡터의 크기와 단위벡터 

$ \begin{Vmatrix} v \end{Vmatrix}  = \sqrt{\Sigma^n_{i=1}{v_i^2} }$

In [25]:
v = np.array([1,2,3,4,5,7,9])
v_dim = len(v)
v_mag = np.linalg.norm(v)
print(v_dim)
print(v_mag)

7
13.601470508735444


단위벡터
$ \hat{v} = \frac{1}{\begin{Vmatrix}v\end{Vmatrix}} v$


벡터의 내적 : $ \delta = \displaystyle\sum_{i=1}^{n} a_i b_i$

벡터의 내적은 두 벡터사이에 similarity (유사성)을 표현하거나 mapping의 척도로 해석할 수 있다. 
두 변수 사이에 정규화된 내적은 피어슨상관계수가 된다. 

In [27]:
v = np.array([4,5,6])
w = np.array([10,20,30])
print(np.dot(v,w))

320


분배법칙을 적용해보자.

In [28]:
a = np.array([0,1,2])
b = np.array([3,5,8])
c = np.array([13,23,22])
print(np.dot(a,b+c))
print(np.dot(a,b)+np.dot(a,c))

88
88


아다마르 곱도 계산해보자.(Hardamard product) 
A $\odot$ B

In [29]:
print(a*b)

[ 0  5 16]
